---
- hosts: localhost
  become: true
  
  vars:
    jenkins_hostname: skytest.jenkins.com
    java_packages:
      - java-1.8.0-openjdk

  roles:
#    - role: ansible-role-java
    - role: ansible-role-jenkins
